project:
  type: website

website:
  title: "Your Name"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - teaching.qmd
      - cv.qmd

format:
  html:
    theme: cosmo
    toc: true
